#!/usr/bin/python3 -tt
# SPDX-License-Identifier: GPL-2.0-or-later
#
#   testclient_sendfile.py
#   XML-RPC test client which just sends an XML file to the given rteval server
#
#   Copyright 2009 - 2013   David Sommerseth <davids@redhat.com>
#

import sys
import libxml2
from argparse import ArgumentParser

sys.path.append('../rteval')
import rtevalclient

if __name__ == '__main__':
    parser = ArgumentParser(version="%prog v0.1")

    parser.add_argument("-r", "--report", action="store", dest="report", default="summary.xml",
                      help="Which XML report to send to the XML-RPC server  (default: %default)",
                      metavar="FILE")
    parser.add_argument("-X", "--xmlrpc-submit", dest="xmlrpchost", default="localhost:65432",
                      help="Hostname to the XML-RPC server to send the data (default: %default)",
                      metavar="HOST[:PORT]")

    opts = parser.parse_args()

    d = libxml2.parseFile(opts.report)

    client = rtevalclient.rtevalclient("http://%s/rteval/API1/" % opts.xmlrpchost)

    status = client.SendReport(d)
    print "SendReport(xmlDoc): %s" % status
else:
    raise Exception, "This is a standalone program, not a module to be imported"
